### ISSUE TITLE
Push tasty-1.2 fixes to hackage?

### ISSUE THREAD

**Issue by endgame** [futurice/haskell-tdigest#30]
I see you have updated the tasty dependencies in your code, but the version on hackage still depends on tasty < 1.2. This means that tdigest does not currently build on nixpkgs master, where tasty-1.2 has landed.

Would you be able to push metadata revisions for fixed packages? Thanks.

**Comment by phadej** [comment]
As I commented in https://github.com/phadej/insert-ordered-containers/issues/27

I'm fine if nixpkgs temporarily doesn't run tests of `insert-ordered-containers` (or `tdigest` or Stackage)
- I don't want to make releases/revisions for test reasons only; they don't add much to users of the library (bounds in tests don't restrict install plans)
- I don't want to remove bounds either, because then I'll receive bug reports that tests possibly fail to compile.

I have CI. Stackage and Nixpkgs additional CI is a bonus, but I'm ok if it's not run.

I'd appreciate if nixpkgs simply omitted test bounds and tried to compile test suites, and then reported if tests fail to compile (or if new versions of test dependencies make tests fail, which is not impossible either).
